### ISSUE TITLE
Missing resources for autoencoders.lyx

### ISSUE THREAD

**Issue by Qiang-Feng** [ic-projects/autoencoders-website#1]
You forgot to add the Laurence/Pictures directory.

**Comment by jordanspooner** [comment]
I'm disgusted by this, Laurence.

**Comment by jordanspooner** [comment]
@PK398 please fix this.

**Comment by PK398** [comment]
@jordanspooner my apologies. I have now fixed it. I have also added a readme page. Ur welcome xx

**Comment by PK398** [comment]
@Qiang-Feng how dare u unassign me. @lsquires quite disappointed mate

**Comment by PK398** [comment]
I believe the issue has been resolved

**Comment by Qiang-Feng** [comment]
@lsquires Please fix this

**Comment by lsquires** [comment]
thanks @onsmirnov for fixing it

**Comment by PK398** [comment]
@onsmirnov u did a very bad job. Disappointed in u @lsquires for thinking @onsmirnov fixed it.

**Comment by Qiang-Feng** [comment]
#982d32541d25d536bc4c8293f97f8d4c54e88fc3
