### ISSUE TITLE
JavaScript Police

### ISSUE THREAD

**Issue by PK398** [ic-projects/autoencoders-website#2]
@onsmirnov @Qiang-Feng @jordanspooner @lsquires No javascript found, plz fix.

**Comment by lsquires** [comment]
@PK398 pls fix this k thx

**Comment by Qiang-Feng** [comment]
k fixd

**Comment by PK398** [comment]
No JavaScript has been found. plz fix. @lsquires @Qiang-Feng @onsmirnov @jordanspooner

**Comment by Qiang-Feng** [comment]
JavaScript is found at website/js/... Fixed @PK398
